import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadAgentMetadataUpdatedPayload as ContractsThreadAgentMetadataUpdatedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  AgentPlanCreatedPayload as ContractsAgentPlanCreatedPayloadSchema,
  AgentPlanDeletedPayload as ContractsAgentPlanDeletedPayloadSchema,
  AgentPlanUpdatedPayload as ContractsAgentPlanUpdatedPayloadSchema,
  AgentPlanStatusChangedPayload as ContractsAgentPlanStatusChangedPayloadSchema,
  AgentTaskUpsertedPayload as ContractsAgentTaskUpsertedPayloadSchema,
  AgentSharedUpdateAppendedPayload as ContractsAgentSharedUpdateAppendedPayloadSchema,
  AgentContractUpsertedPayload as ContractsAgentContractUpsertedPayloadSchema,
  AgentCoordinationMessageUpsertedPayload as ContractsAgentCoordinationMessageUpsertedPayloadSchema,
  AgentReviewUpsertedPayload as ContractsAgentReviewUpsertedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;
export const ThreadAgentMetadataUpdatedPayload = ContractsThreadAgentMetadataUpdatedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;

export const AgentPlanCreatedPayload = ContractsAgentPlanCreatedPayloadSchema;
export const AgentPlanUpdatedPayload = ContractsAgentPlanUpdatedPayloadSchema;
export const AgentPlanStatusChangedPayload = ContractsAgentPlanStatusChangedPayloadSchema;
export const AgentPlanDeletedPayload = ContractsAgentPlanDeletedPayloadSchema;
export const AgentTaskUpsertedPayload = ContractsAgentTaskUpsertedPayloadSchema;
export const AgentSharedUpdateAppendedPayload = ContractsAgentSharedUpdateAppendedPayloadSchema;
export const AgentContractUpsertedPayload = ContractsAgentContractUpsertedPayloadSchema;
export const AgentCoordinationMessageUpsertedPayload =
  ContractsAgentCoordinationMessageUpsertedPayloadSchema;
export const AgentReviewUpsertedPayload = ContractsAgentReviewUpsertedPayloadSchema;
