export const AGENT_DELEGATION_DEVELOPER_INSTRUCTIONS = [
  "T3 Code can launch parallel subagents through t3.spawn_workers.",
  "",
  "Owner-thread default: look for a useful worker to spawn before doing sequential work yourself.",
  "Treat t3.spawn_workers as a normal first move, not a last resort for large tasks. It is encouraged for small independent commands, quick checks, test runs, repo scans, filesystem discovery, focused code reading, and verification steps whenever the owner can keep planning, reading, or coordinating in parallel.",
  "At the start of each user task, decide what can run independently and call t3.spawn_workers early. Do not wait until you have finished the main investigation if a worker can gather facts or run commands now.",
  "Strongly prefer spawning workers when the task touches multiple projects, packages, modules, folders, repos, commands, or independently testable scopes; when implementation and verification can proceed independently; when repository guidelines require validation in multiple scopes; or when independent investigation would reduce risk.",
  "",
  "For broad discovery prompts such as looking through all repos, every folder, worktrees, branches, caches, logs, or generated artifacts: first enumerate candidate scopes, then spawn workers in batches of up to 8. Assign each worker a repo, folder group, or command group to inspect and report back.",
  "For command or test prompts: prefer assigning one worker to run the command/check/test while the owner continues with related inspection or planning.",
  "",
  "For each project or package with meaningful changes and required tests, default to two workers:",
  "- <project>-implementation: implement the scoped code change.",
  "- <project>-verification: write, run, or repair the relevant tests and checks for that scope.",
  "",
  "Avoid spawning workers only when the task is truly atomic, there is no useful independent command or inspection to run, the edit is highly coupled, or delegation would clearly add more coordination than value.",
  "Worker prompts must include the project or package scope, allowed paths, blocked paths, success criteria, required tests or checks, and expected report_to_owner behavior.",
  "Workers cannot spawn workers. If your prompt says you are a worker subagent, do not call t3.spawn_workers; report progress, blockers, changed files, and test results with t3.report_to_owner.",
  "If there is any plausible independent work and you choose not to spawn workers, briefly state why before continuing.",
].join("\n");
